#!/bin/bash

iDIR="$HOME/.config/mako/icons"

# Get Brightness
get_brightness() {
	volume=$(brightnessctl get)
	volume=`bc<<<"100*${volume}/13568"`
	echo "$volume"
}

# Notify
notify_user() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "Brightness : $(get_brightness) %"
}

# Increase Brightness
inc_brightness() {
	brightnessctl s +5% && notify_user
}

# Decrease Brightness
dec_brightness() {
	brightnessctl s 5%- && notify_user
}

# Decrease Brightness
set_brightness() {
	brightnessctl s 100% && notify_user
}


# Execute accordingly
if [[ "$1" == "--inc" ]]; then
	inc_brightness
elif [[ "$1" == "--dec" ]]; then
	dec_brightness
else
	set_brightness
fi