version: "3"

networks:
  metrics:
    external: false

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    networks: [metrics]
    ports:
      - "8086:8086"
    volumes:
      - /opt/docker/grafana_stack/influxdb/data:/var/lib/influxdb
      - /opt/docker/grafana_stack/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - /opt/docker/grafana_stack/influxdb/init:/docker-entrypoint-initdb.d
    environment:
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME} # sourced from .env
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD} # sourced from .env

  telegraf:
    image: telegraf:latest
    restart: always
    container_name: telegraf
    user: telegraf:114
    networks: [metrics]
    volumes:
      - /opt/docker/grafana_stack/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /:/mnt/system_root:ro
      - /mnt/datadisk:/mnt/system_data:ro
      - /var/run/docker.sock:/var/run/docker.sock
# Link devices for smart input plugin. But wont work anyways
#    devices:
#      - /dev/sda:/dev/sda
#      - /dev/nvme0:/dev/nvme0


  chronograf:
    container_name: chronograf
    restart: always
    image: chronograf:latest
    ports:
      - "8889:8888"
    depends_on:
      - influxdb
    networks: [metrics]
    environment:
      - INFLUXDB_URL=http://influxdb:8086 # needs to match container_name
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME} # sourced from .env
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD} # sourced from .env

  grafana:
    container_name: grafana
    restart: always
    image: grafana/grafana-enterprise:latest
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    networks: [metrics]
    volumes:
      - /opt/docker/grafana_stack/grafana/data:/var/lib/grafana
      - /opt/docker/grafana_stack/grafana/ini:/etc/grafana/
