#!/bin/bash
#
# Plugin to monitor rsyncd.
# based on previous work by jintxo
#
# Parameters understood:
#
# 	config   (required)
# 	autoconf (optional)
#
#

mktempfile () {
mktemp -t $1
}

RSYNCD_LOG=${logfile:-/var/log/rsyncd.log}
LOGTAIL=${logtail:-`which logtail`}
STATEFILE=/var/lib/munin-node/plugin-state/rsync/rsync-bytes.offset

if [ "$1" = "autoconf" ]; then
        if [ -f "${RSYNCD_LOG}" -a -n "${LOGTAIL}" -a -x "${LOGTAIL}" ] ; then
		echo yes
		exit 0
	else
		echo no
		exit 1
	fi
fi

if [ "$1" = "config" ]; then
	echo 'graph_title Rsync Server Bytes'
        echo 'graph_args --base 1000 -l 0'
	echo 'graph_order send recv'
	echo 'graph_category rsync'
	echo 'graph_vlabel Bytes'
	echo 'send.label Bytes Send'
	echo 'recv.label Bytes Recv'
	echo 'send.type COUNTER'
	echo 'recv.type COUNTER'
	exit 0
fi

send=U
recv=U

TEMP_FILE=`mktempfile munin-rsync-bytes.XXXXXX`

if [ -n "$TEMP_FILE" -a -f "$TEMP_FILE" ]
then
	$LOGTAIL ${RSYNCD_LOG} $STATEFILE | grep ".* Total .* bytes\." > ${TEMP_FILE}
	send=`cat ${RSYNCD_LOG} | sed -ne 's/.*sent //;s/bytes.*//p' | awk '{sum+=$1}END{print sum}'`
	recv=`cat ${RSYNCD_LOG} | sed -ne 's/.*received //;s/ bytes.*//p' | awk '{sum+=$1}END{print sum}'`
	/bin/rm -f $TEMP_FILE
fi

echo "send.value ${send}"
echo "recv.value ${recv}"
